"""empty message

Revision ID: 466efa65df3a
Revises: c0260362c10a
Create Date: 2020-06-12 18:46:45.342914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466efa65df3a'
down_revision = 'c0260362c10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_repos', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('user_repos_username_key', 'user_repos', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_repos_username_key', 'user_repos', ['username'])
    op.alter_column('user_repos', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
